export const GET_USER_DETAILS_REQUESTED = 'GET_USER_DETAILS_REQUESTED'
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS'
export const GET_USER_DETAILS_FAILED = 'GET_USER_DETAILS_FAILED'

export const DELETE_USER_REQUESTED = 'DELETE_USER_REQUESTED'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED'
export const DELETE_USER_RESET = 'DELETE_USER_RESET'

export const EDIT_USER_REQUESTED = 'EDIT_USER_REQUESTED'
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'
export const EDIT_USER_FAILED = 'EDIT_USER_FAILED'
export const EDIT_USER_RESET = 'EDIT_USER_RESET'

export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB'
